# Generated by Django 3.2.10 on 2022-07-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelationTuples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace_id', models.IntegerField()),
                ('object', models.CharField(max_length=64)),
                ('relation', models.CharField(max_length=64)),
                ('subject_id', models.CharField(blank=True, max_length=64, null=True)),
                ('subject_set_namespace_id', models.IntegerField(blank=True, null=True)),
                ('subject_set_object', models.CharField(blank=True, max_length=64, null=True)),
                ('subject_set_relation', models.CharField(blank=True, max_length=64, null=True)),
                ('commit_time', models.DateTimeField()),
            ],
        ),
    ]
