# Generated by Django 3.2.10 on 2022-09-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rbac', '0002_alter_ketorelationtuples_commit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketorelationtuples',
            name='object',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ketorelationtuples',
            name='subject_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ketorelationtuples',
            name='subject_set_object',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ketorelationtuples',
            name='subject_set_relation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
